import React from 'react'
import '../styles/About.css'
import Footer from '../components/Footer';

export default function About() {
  return (
    <div>
      <section className="about" id="about">
        <h1 className='about-line'>Who <span>Are</span> We!</h1>
      </section>
      <section className="history" id="history">
        <div className="underline"></div>
        <h2>Our History</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem sed delectus a facilis voluptates, maxime soluta odit placeat perspiciatis nam porro illo optio quae neque sequi cum molestiae saepe consequatur eaque dolores tempore magnam officia, molestias ipsam! Illum repudiandae voluptatem dolorem ut eligendi, voluptate nostrum veniam, recusandae, vel incidunt nemo dicta fugit! Laborum aliquid ratione minima tempore, repellat est iusto quidem possimus eligendi, assumenda repudiandae accusantium atque harum corrupti, nobis cupiditate ipsam vero architecto quaerat necessitatibus saepe maxime rerum ex praesentium? Impedit vero fugiat similique quaerat quas! Modi, tenetur a facere quo eligendi quisquam quibusdam architecto neque eum exercitationem, aut pariatur cupiditate necessitatibus voluptates molestias dolor veniam totam suscipit et minima, dignissimos sequi deserunt! Placeat et soluta sed ipsa vel perferendis voluptatum, nostrum mollitia veritatis doloremque debitis ipsum rerum. Minima doloremque quisquam modi id totam rem fuga expedita similique? Quas debitis omnis ipsam qui iusto eveniet ab quos! Voluptatem enim corrupti delectus magni, qui laboriosam nam similique animi mollitia accusamus perferendis eaque placeat, adipisci reiciendis, id aspernatur alias consectetur sunt ad officiis! Culpa, et similique suscipit porro vero fugit? Nobis, accusantium distinctio vero nostrum aspernatur facilis facere, repellat, eveniet quod eos minima. Nesciunt nobis fugiat perspiciatis quaerat laborum neque eveniet.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem sed delectus a facilis voluptates, maxime soluta odit placeat perspiciatis nam porro illo optio quae neque sequi cum molestiae saepe consequatur eaque dolores tempore magnam officia, molestias ipsam! Illum repudiandae voluptatem dolorem ut eligendi, voluptate nostrum veniam, recusandae, vel incidunt nemo dicta fugit! Laborum aliquid ratione minima tempore, repellat est iusto quidem possimus eligendi, assumenda repudiandae accusantium atque harum corrupti, nobis cupiditate ipsam vero architecto quaerat necessitatibus saepe maxime rerum ex praesentium? Impedit vero fugiat similique quaerat quas! Modi, tenetur a facere quo eligendi quisquam quibusdam architecto neque eum exercitationem, aut pariatur cupiditate necessitatibus voluptates molestias dolor veniam totam suscipit et minima, dignissimos sequi deserunt! Placeat et soluta sed ipsa vel perferendis voluptatum, nostrum mollitia veritatis doloremque debitis ipsum rerum. Minima doloremque quisquam modi id totam rem fuga expedita similique? Quas debitis omnis ipsam qui iusto eveniet ab quos! Voluptatem enim corrupti delectus magni, qui laboriosam nam similique animi mollitia accusamus perferendis eaque placeat, adipisci reiciendis, id aspernatur alias consectetur sunt ad officiis! Culpa, et similique suscipit porro vero fugit? Nobis, accusantium distinctio vero nostrum aspernatur facilis facere, repellat, eveniet quod eos minima. Nesciunt nobis fugiat perspiciatis quaerat laborum neque eveniet.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem sed delectus a facilis voluptates, maxime soluta odit placeat perspiciatis nam porro illo optio quae neque sequi cum molestiae saepe consequatur eaque dolores tempore magnam officia, molestias ipsam! Illum repudiandae voluptatem dolorem ut eligendi, voluptate nostrum veniam, recusandae, vel incidunt nemo dicta fugit! Laborum aliquid ratione minima tempore, repellat est iusto quidem possimus eligendi, assumenda repudiandae accusantium atque harum corrupti, nobis cupiditate ipsam vero architecto quaerat necessitatibus saepe maxime rerum ex praesentium? Impedit vero fugiat similique quaerat quas! Modi, tenetur a facere quo eligendi quisquam quibusdam architecto neque eum exercitationem, aut pariatur cupiditate necessitatibus voluptates molestias dolor veniam totam suscipit et minima, dignissimos sequi deserunt! Placeat et soluta sed ipsa vel perferendis voluptatum, nostrum mollitia veritatis doloremque debitis ipsum rerum. Minima doloremque quisquam modi id totam rem fuga expedita similique? Quas debitis omnis ipsam qui iusto eveniet ab quos! Voluptatem enim corrupti delectus magni, qui laboriosam nam similique animi mollitia accusamus perferendis eaque placeat, adipisci reiciendis, id aspernatur alias consectetur sunt ad officiis! Culpa, et similique suscipit porro vero fugit? Nobis, accusantium distinctio vero nostrum aspernatur facilis facere, repellat, eveniet quod eos minima. Nesciunt nobis fugiat perspiciatis quaerat laborum neque eveniet.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem sed delectus a facilis voluptates, maxime soluta odit placeat perspiciatis nam porro illo optio quae neque sequi cum molestiae saepe consequatur eaque dolores tempore magnam officia, molestias ipsam! Illum repudiandae voluptatem dolorem ut eligendi, voluptate nostrum veniam, recusandae, vel incidunt nemo dicta fugit! Laborum aliquid ratione minima tempore, repellat est iusto quidem possimus eligendi, assumenda repudiandae accusantium atque harum corrupti, nobis cupiditate ipsam vero architecto quaerat necessitatibus saepe maxime rerum ex praesentium? Impedit vero fugiat similique quaerat quas! Modi, tenetur a facere quo eligendi quisquam quibusdam architecto neque eum exercitationem, aut pariatur cupiditate necessitatibus voluptates molestias dolor veniam totam suscipit et minima, dignissimos sequi deserunt! Placeat et soluta sed ipsa vel perferendis voluptatum, nostrum mollitia veritatis doloremque debitis ipsum rerum. Minima doloremque quisquam modi id totam rem fuga expedita similique? Quas debitis omnis ipsam qui iusto eveniet ab quos! Voluptatem enim corrupti delectus magni, qui laboriosam nam similique animi mollitia accusamus perferendis eaque placeat, adipisci reiciendis, id aspernatur alias consectetur sunt ad officiis! Culpa, et similique suscipit porro vero fugit? Nobis, accusantium distinctio vero nostrum aspernatur facilis facere, repellat, eveniet quod eos minima. Nesciunt nobis fugiat perspiciatis quaerat laborum neque eveniet.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem sed delectus a facilis voluptates, maxime soluta odit placeat perspiciatis nam porro illo optio quae neque sequi cum molestiae saepe consequatur eaque dolores tempore magnam officia, molestias ipsam! Illum repudiandae voluptatem dolorem ut eligendi, voluptate nostrum veniam, recusandae, vel incidunt nemo dicta fugit! Laborum aliquid ratione minima tempore, repellat est iusto quidem possimus eligendi, assumenda repudiandae accusantium atque harum corrupti, nobis cupiditate ipsam vero architecto quaerat necessitatibus saepe maxime rerum ex praesentium? Impedit vero fugiat similique quaerat quas! Modi, tenetur a facere quo eligendi quisquam quibusdam architecto neque eum exercitationem, aut pariatur cupiditate necessitatibus voluptates molestias dolor veniam totam suscipit et minima, dignissimos sequi deserunt! Placeat et soluta sed ipsa vel perferendis voluptatum, nostrum mollitia veritatis doloremque debitis ipsum rerum. Minima doloremque quisquam modi id totam rem fuga expedita similique? Quas debitis omnis ipsam qui iusto eveniet ab quos! Voluptatem enim corrupti delectus magni, qui laboriosam nam similique animi mollitia accusamus perferendis eaque placeat, adipisci reiciendis, id aspernatur alias consectetur sunt ad officiis! Culpa, et similique suscipit porro vero fugit? Nobis, accusantium distinctio vero nostrum aspernatur facilis facere, repellat, eveniet quod eos minima. Nesciunt nobis fugiat perspiciatis quaerat laborum neque eveniet.</p>
      </section>
      <Footer/>
    </div>
  )
}